mysqlServer:
  server: localhost:3306
  username: root
  password: QTMgzeWmx5lzLbRUrScWWLCMhPXwdx3+OKECs4YcU7Ovj+T27kEHZgun9lyTHDuoI9ETkGlIi7ym7XWqT/EXEQ==
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJo8RXWa88I03HCJ0wmnZC0IQsHrIO+WHCs2OwaEqEzCfJv+2M6o4vxPVn4Qy2czR5jQecm++vzMyKY1UYc5yRsCAwEAAQ==

redisServer:
  host: localhost
  port: 6379

mail:
  url: localhost:9002
  username: MineWorldServer@163.com
  password: cptbtptp123
  content: Click here to activate your account
  subject: 来自快乐购的激活邮件