mysqlServer:
  server: localhost:3306
  username: root
  password: rootroot

redisServer:
  host: localhost
  port: 6379

mail:
  url: localhost:9002
  username: MineWorldServer@163.com
  password: cptbtptp123
  content: Click here to activate your account
  subject: 来自快乐购的激活邮件