server:
  port: 9004
  context-path: /happymall/admin/

spring:
  datasource:
    name: happymall_localhost
    url: jdbc:mysql://localhost:3306/happymall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/webapp/

mybatis:
  mapper-locations: classpath:mapper/**/**/*.xml
  type-aliases-package: com.xul.happymall.admin.domain
  type-handlers-package: com.xul.happymall.admin.dao
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
